"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_routes_1 = require("../modules/auth/auth.routes");
const admin_movies_routes_1 = require("../modules/admin-movies/admin-movies.routes");
const admin_stories_routes_1 = require("../modules/admin-stories/admin-stories.routes");
const categories_routes_1 = require("../modules/categories/categories.routes");
const comments_routes_1 = require("../modules/comments/comments.routes");
const content_routes_1 = require("../modules/content/content.routes");
const history_routes_1 = require("../modules/history/history.routes");
const movies_routes_1 = require("../modules/movies/movies.routes");
const notifications_routes_1 = require("../modules/notifications/notifications.routes");
const ratings_routes_1 = require("../modules/ratings/ratings.routes");
const stories_routes_1 = require("../modules/stories/stories.routes");
const transaction_routes_1 = require("../modules/transactions/transaction.routes");
const users_routes_1 = require("../modules/users/users.routes");
const socket_routes_1 = require("../modules/socket/socket.routes");
const system_routes_1 = require("../modules/system/system.routes");
const router = (0, express_1.Router)();
router.use(auth_routes_1.default);
router.use(admin_movies_routes_1.default);
router.use(admin_stories_routes_1.default);
router.use(categories_routes_1.default);
router.use(comments_routes_1.default);
router.use(history_routes_1.default);
router.use(movies_routes_1.default);
router.use(notifications_routes_1.default);
router.use(ratings_routes_1.default);
router.use(stories_routes_1.default);
router.use(users_routes_1.default);
router.use(content_routes_1.default);
router.use(transaction_routes_1.default);
router.use(socket_routes_1.default);
router.use(system_routes_1.default);
exports.default = router;
